%Shows correcnteds of algorithm
%takes theta generated by allOthers a parameters
function [ connectness ] = test( theta )
    
    testData = load('mnistTest.mat');
    testX = testData.images;
    testy = testData.labels;
    testSize = 1000;
    connectness = 0;
    for i=1:testSize;
        % compare against each class
        argmax = 0;
        hmaxVal = 1;
        for k=1:10
            s = dot(testX(i, :), theta(k,:));
            h = exp(s)/(1+exp(s));
            if h < hmaxVal
                hmaxVal = h;
                argmax = k-1;
            end
        end
        if argmax == testy(i)
            connectness = connectness + 1;
        end
    end
    connectness = connectness/testSize;
end

